### ISSUE TITLE
build sys: linux: avoid requiring LD_LIBRARY_PATH for $HFS/dsolib

### ISSUE THREAD

**Issue by mistafunk** [Esri/palladio#37]
at runtime, our dso is depending on libraries in $HFS/dsolib. as it does not seem to be possible to embed literally "$HFS/dsolib" in the linker RPATH we need to require LD_LIBRARY_PATH before launching houdini which is ugly.

is there a way to avoid LD_LIBRARY_PATH?

while at it, also investigate if there is a reasonable way to limit symbol visibility (i.e. is there a stable set of symbols we can whitelist for palladio so it still loads and runs?)

**Comment by Svenito** [comment]
Mixing boost versions from Houdini and system is not a great idea. I have experienced segfaults with smart pointers because of this in 16.5. In 17.0 I am forced to link to both boost and hboost though, where things work a little better. The reason I need both is because my project links to libraries that require regular boost. So it's all getting somewhat messy. Just giving you a heads up on this lovely hboost future :)

You should be able to expand $HFS when setting the rpath though.

**Comment by mistafunk** [comment]
@Svenito i've tested adding `$HFS` to the RPATH and this does not work. i believe for security reasons, the linux dynamic linker only knows $ORIGIN as a special value (i.e. it is not an env var, even if it looks like that).

i'm going to try to privately link a static copy of boost to palladio. this should work if we take care to not depend on hboost and make sure the symbol visibility is correctly handled (i.e. not using global variables with "our" boost or just in anon namespaces etc)

**Comment by Svenito** [comment]
What I meant was that you should know the $HFS value at compile time and so it is expanded when the rpath is set in the compiler args.

**Comment by mistafunk** [comment]
avoided this problem by switching to internal static boost libraries (thanks to conan for making this a breeze).
